project:
  type: website
  output-dir: docs

website:
  title: "Michael Diao's Blog"
  navbar:
    pinned: true
    collapse-below: lg
    right:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Research"
        href: research.qmd
  google-analytics: G-Y9Q6Z3H9NW
  site-url: "https://www.mzydiao.com"
  site-path: "/"
format:
  html:
    html-math-method: katex
    theme:
      - cosmo
      - custom.scss
    css: styles.css



